CREATE TABLE `__TABLE_NAME__` (
  `wr_id` int(11) NOT NULL AUTO_INCREMENT,
  `wr_num` int(11) NOT NULL DEFAULT '0',
  `wr_reply` varchar(10) NOT NULL,
  `wr_parent` int(11) NOT NULL DEFAULT '0',
  `wr_is_comment` tinyint(4) NOT NULL DEFAULT '0',
  `wr_comment` int(11) NOT NULL DEFAULT '0',
  `wr_comment_reply` varchar(5) NOT NULL,
  `ca_name` varchar(255) NOT NULL,
  `wr_option` set('html1','html2','secret','mail') NOT NULL,
  `wr_subject` varchar(255) NOT NULL,
  `wr_content` text NOT NULL,
  `wr_link1` text NOT NULL,
  `wr_link2` text NOT NULL,
  `wr_link1_hit` int(11) NOT NULL DEFAULT '0',
  `wr_link2_hit` int(11) NOT NULL DEFAULT '0',
  `wr_hit` int(11) NOT NULL DEFAULT '0',
  `wr_good` int(11) NOT NULL DEFAULT '0',
  `wr_nogood` int(11) NOT NULL DEFAULT '0',
  `mb_id` varchar(20) NOT NULL,
  `wr_password` varchar(255) NOT NULL,
  `wr_name` varchar(255) NOT NULL,
  `wr_email` varchar(255) NOT NULL,
  `wr_homepage` varchar(255) NOT NULL,
  `wr_datetime` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `wr_file` tinyint(4) NOT NULL DEFAULT '0',
  `wr_last` varchar(19) NOT NULL,
  `wr_ip` varchar(255) NOT NULL,
  `wr_facebook_user` varchar(255) NOT NULL,
  `wr_twitter_user` varchar(255) NOT NULL,

  `wr_dice1` int(11) NOT NULL DEFAULT '0',
  `wr_dice2` int(11) NOT NULL DEFAULT '0',
  `wr_log` text NOT NULL,
  `wr_item` int(11) NOT NULL DEFAULT '0',
  `wr_item_log` varchar(255) NOT NULL DEFAULT '',
  `wr_action` varchar(255) NOT NULL DEFAULT '',

  `wr_secret` int(11) NOT NULL DEFAULT '0',
  `wr_adult` int(11) NOT NULL DEFAULT '0',
  `wr_wide` int(11) NOT NULL DEFAULT '0',
  `wr_plip` int(11) NOT NULL DEFAULT '0',
  `wr_noname` int(11) NOT NULL DEFAULT '0',
  `wr_ing` int(11) NOT NULL DEFAULT '0',

  `ch_id` int(11) NOT NULL DEFAULT '0',
  `ch_side` int(11) NOT NULL DEFAULT '0',
  `ch_class` int(11) NOT NULL DEFAULT '0',
  `ti_id` int(11) NOT NULL DEFAULT '0',
  `ma_id` int(11) NOT NULL DEFAULT '0',
  `wr_width` int(11) NOT NULL DEFAULT '0',
  `wr_height` int(11) NOT NULL DEFAULT '0',
  `wr_url` varchar(255) NOT NULL DEFAULT '',
  `wr_type` varchar(255) NOT NULL DEFAULT '',



  `wr_1` varchar(255) NOT NULL DEFAULT '',
  `wr_2` varchar(255) NOT NULL DEFAULT '',
  `wr_3` varchar(255) NOT NULL DEFAULT '',
  `wr_4` varchar(255) NOT NULL DEFAULT '',
  `wr_5` varchar(255) NOT NULL DEFAULT '',
  `wr_6` varchar(255) NOT NULL DEFAULT '',
  `wr_7` varchar(255) NOT NULL DEFAULT '',
  `wr_8` varchar(255) NOT NULL DEFAULT '',
  `wr_9` varchar(255) NOT NULL DEFAULT '',
  `wr_10` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`wr_id`),
  KEY `wr_num_reply_parent` (`wr_num`,`wr_reply`,`wr_parent`),
  KEY `wr_is_comment` (`wr_is_comment`,`wr_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;